import { Scholarship } from '../types';

// NOTE: Dates here are deliberately set to past years in some cases to demonstrate 
// the Auto-Reset / Recurring Logic in the ScholarshipEngine.

export const scholarshipDatabase: Scholarship[] = [
  // --- Existing Scholarships ---
  {
    id: "s_01",
    name: "PMKVY 4.0 Skill Certification",
    provider: "Govt of India (MSDE)",
    category: "Vocational",
    providerType: "Government",
    level: "National",
    incomeLimit: undefined,
    socialGroup: ["All"],
    careerGoal: ["Vocational", "Engineering", "STEM"],
    benefits: "Free training + ₹500 stipend + Certification",
    startDate: "2023-01-01",
    deadline: "2023-12-31", // Will auto-renew to current year
    isRecurring: true,
    lastVerified: "2024-01-15T10:00:00Z",
    applyLink: "https://www.pmkvyofficial.org"
  },
  {
    id: "s_02",
    name: "NSP Central Sector Scheme",
    provider: "Ministry of Education",
    category: "Merit",
    providerType: "Government",
    level: "National",
    incomeLimit: 8,
    socialGroup: ["All"],
    careerGoal: ["Engineering", "Medical", "STEM", "General"],
    benefits: "₹10,000 - ₹20,000 per annum",
    startDate: "2023-07-01",
    deadline: "2023-10-31", // Recurring, usually opens July-Oct
    isRecurring: true,
    lastVerified: "2024-02-01T10:00:00Z",
    applyLink: "https://scholarships.gov.in"
  },
  {
    id: "s_03",
    name: "ONGC Sports Scholarship",
    provider: "ONGC",
    category: "Sports",
    providerType: "PSU",
    level: "National",
    incomeLimit: undefined,
    socialGroup: ["All"],
    careerGoal: ["Sports"],
    benefits: "₹15,000 - ₹25,000 per month + Kit allowance",
    startDate: "2024-04-01",
    deadline: "2024-06-15",
    isRecurring: true,
    applyLink: "https://ongcindia.com"
  },
  {
    id: "s_04",
    name: "Post Matric Scholarship for Minorities",
    provider: "Ministry of Minority Affairs",
    category: "Minority",
    providerType: "Government",
    level: "National",
    incomeLimit: 2,
    socialGroup: ["Minority"],
    careerGoal: ["General", "STEM", "MBA", "Medical"],
    benefits: "Admission + Tuition fee reimbursement",
    startDate: "2023-08-01",
    deadline: "2023-11-15",
    isRecurring: true,
    applyLink: "https://scholarships.gov.in"
  },
  {
    id: "s_05",
    name: "Dhirubhai Ambani Scholarship",
    provider: "Reliance Foundation",
    category: "Merit",
    providerType: "Foundation",
    level: "National",
    incomeLimit: 15,
    socialGroup: ["All"],
    careerGoal: ["Engineering", "Medical"],
    benefits: "Up to ₹4 Lakhs for duration of course",
    startDate: "2024-06-01",
    deadline: "2024-08-31",
    isRecurring: true,
    applyLink: "https://www.reliancefoundation.org"
  },
  {
    id: "s_06",
    name: "HDFC Badte Kadam",
    provider: "HDFC Bank",
    category: "Means",
    providerType: "Private",
    level: "National",
    incomeLimit: 6,
    socialGroup: ["All"],
    careerGoal: ["General", "STEM", "Vocational"],
    benefits: "₹30,000 - ₹1,00,000 one time",
    deadline: "2025-09-15",
    isRecurring: false, // One time or irregular
    applyLink: "https://www.hdfcbank.com"
  },
  {
    id: "s_07",
    name: "Tata Trusts Medical & Healthcare",
    provider: "Tata Trusts",
    category: "Research",
    providerType: "Foundation",
    level: "National",
    incomeLimit: undefined,
    socialGroup: ["All"],
    careerGoal: ["Medical", "Research"],
    benefits: "Variable grant based on need (approx ₹2-5 Lakhs)",
    startDate: "2024-05-01",
    deadline: "2024-07-20",
    isRecurring: true,
    applyLink: "https://www.tatatrusts.org"
  },
  {
    id: "s_08",
    name: "National Overseas Scholarship",
    provider: "Ministry of Social Justice",
    category: "Research",
    providerType: "Government",
    level: "International",
    incomeLimit: 8,
    socialGroup: ["SC", "ST"],
    careerGoal: ["Research", "STEM", "MBA"],
    benefits: "Full tuition + Living expenses for study abroad",
    startDate: "2024-02-15",
    deadline: "2024-03-31",
    isRecurring: true,
    applyLink: "https://nosmsje.gov.in"
  },
  {
    id: "s_09",
    name: "Viksit Bharat Fellowship",
    provider: "NITI Aayog",
    category: "Research",
    providerType: "Government",
    level: "National",
    incomeLimit: undefined,
    socialGroup: ["All"],
    careerGoal: ["Research", "STEM"],
    benefits: "₹50,000/month for policy research",
    deadline: "2025-05-01",
    isRecurring: false,
    applyLink: "https://niti.gov.in"
  },
  {
    id: "s_10",
    name: "IDFC FIRST Bank MBA Scholarship",
    provider: "IDFC FIRST",
    category: "Merit",
    providerType: "Private",
    level: "National",
    incomeLimit: 6,
    socialGroup: ["All"],
    careerGoal: ["MBA"],
    benefits: "₹2 Lakhs for 2 years",
    startDate: "2024-05-01",
    deadline: "2024-07-31",
    isRecurring: true,
    applyLink: "https://www.idfcfirstbank.com"
  },
  {
    id: "s_11",
    name: "Saksham Scholarship (Differently Abled)",
    provider: "AICTE",
    category: "Means",
    providerType: "Government",
    level: "National",
    incomeLimit: 8,
    socialGroup: ["All"],
    careerGoal: ["Engineering", "Vocational"],
    benefits: "₹50,000 per annum",
    startDate: "2023-08-01",
    deadline: "2023-10-31",
    isRecurring: true,
    applyLink: "https://scholarships.gov.in"
  },
  {
    id: "s_12",
    name: "Kishore Vaigyanik Protsahan Yojana (KVPY)",
    provider: "DST",
    category: "Research",
    providerType: "Government",
    level: "National",
    incomeLimit: undefined,
    socialGroup: ["All"],
    careerGoal: ["Research", "STEM"],
    benefits: "Monthly fellowship ₹5,000 - ₹7,000 + Grant",
    startDate: "2024-06-01",
    deadline: "2024-08-15",
    isRecurring: true,
    applyLink: "http://www.kvpy.iisc.ernet.in"
  },

  // --- SPORTS SCHOLARSHIPS ---
  {
    id: "sp_01",
    name: "Khelo India Scholarship",
    provider: "Ministry of Youth Affairs & Sports",
    category: "Sports",
    providerType: "Government",
    level: "National",
    incomeLimit: undefined,
    socialGroup: ["All"],
    careerGoal: ["Sports"],
    benefits: "₹6.28 Lakhs/year for training & diet",
    startDate: "2023-01-01",
    deadline: "2023-12-31",
    isRecurring: true,
    applyLink: "https://kheloindia.gov.in"
  },
  {
    id: "sp_02",
    name: "Target Olympic Podium Scheme (TOPS)",
    provider: "Sports Authority of India",
    category: "Sports",
    providerType: "Government",
    level: "International",
    incomeLimit: undefined,
    socialGroup: ["All"],
    careerGoal: ["Sports"],
    benefits: "Customized training for Olympic hopefuls + Stipend",
    startDate: "2023-01-01",
    deadline: "2023-12-31",
    isRecurring: true,
    applyLink: "https://sportsauthorityofindia.nic.in"
  },
  {
    id: "sp_03",
    name: "SAI Training Schemes",
    provider: "Sports Authority of India",
    category: "Sports",
    providerType: "Government",
    level: "National",
    incomeLimit: undefined,
    socialGroup: ["All"],
    careerGoal: ["Sports"],
    benefits: "Free boarding, lodging, and world-class coaching",
    startDate: "2024-04-01",
    deadline: "2024-06-30",
    isRecurring: true,
    applyLink: "https://sportsauthorityofindia.nic.in"
  },
  {
    id: "sp_04",
    name: "IndianOil Sports Scholarship",
    provider: "Indian Oil Corporation Ltd",
    category: "Sports",
    providerType: "PSU",
    level: "National",
    incomeLimit: undefined,
    socialGroup: ["All"],
    careerGoal: ["Sports"],
    benefits: "Monthly stipend for elite & budding players",
    startDate: "2024-07-01",
    deadline: "2024-09-30",
    isRecurring: true,
    applyLink: "https://iocl.com"
  },
  {
    id: "sp_05",
    name: "AIPSSPB Sports Scholarship",
    provider: "Public Sector Sports Promotion Board",
    category: "Sports",
    providerType: "PSU",
    level: "National",
    incomeLimit: undefined,
    socialGroup: ["All"],
    careerGoal: ["Sports"],
    benefits: "Scholarship & Employment opportunities in PSUs",
    startDate: "2024-08-01",
    deadline: "2024-10-15",
    isRecurring: true,
    applyLink: "https://sportsauthorityofindia.nic.in"
  },
  {
    id: "sp_06",
    name: "GoSports Foundation Scholarship",
    provider: "GoSports Foundation",
    category: "Sports",
    providerType: "Foundation",
    level: "National",
    incomeLimit: undefined,
    socialGroup: ["All"],
    careerGoal: ["Sports"],
    benefits: "Funds for equipment, travel, and high-performance training",
    startDate: "2024-09-01",
    deadline: "2024-11-30",
    isRecurring: true,
    applyLink: "https://www.gosportsfoundation.in"
  },
  {
    id: "sp_07",
    name: "Inspire Institute of Sport (IIS)",
    provider: "JSW Sports",
    category: "Sports",
    providerType: "Private",
    level: "National",
    incomeLimit: undefined,
    socialGroup: ["All"],
    careerGoal: ["Sports"],
    benefits: "Full scholarship for residential training academy",
    startDate: "2024-03-01",
    deadline: "2024-05-31",
    isRecurring: true,
    applyLink: "https://www.inspireinstituteofsport.com"
  },
  {
    id: "sp_08",
    name: "Haryana State Sports Scholarship",
    provider: "Haryana Sports Department",
    category: "Sports",
    providerType: "Government",
    level: "State",
    incomeLimit: undefined,
    socialGroup: ["All"],
    careerGoal: ["Sports"],
    benefits: "Cash awards and monthly stipend for state medalists",
    startDate: "2024-06-01",
    deadline: "2024-08-31",
    isRecurring: true,
    applyLink: "https://haryanasports.gov.in"
  },
  {
    id: "sp_09",
    name: "Maharashtra Sports Scholarship",
    provider: "Maharashtra Sports Department",
    category: "Sports",
    providerType: "Government",
    level: "State",
    incomeLimit: undefined,
    socialGroup: ["All"],
    careerGoal: ["Sports"],
    benefits: "Financial assistance for equipment and diet",
    startDate: "2024-05-01",
    deadline: "2024-07-31",
    isRecurring: true,
    applyLink: "https://mahasports.maharashtra.gov.in"
  },
  {
    id: "sp_10",
    name: "LPU Sports Scholarship",
    provider: "Lovely Professional University",
    category: "Sports",
    providerType: "University",
    level: "University",
    incomeLimit: undefined,
    socialGroup: ["All"],
    careerGoal: ["Sports"],
    benefits: "100% Tuition Fee waiver + Residential facility",
    startDate: "2024-05-01",
    deadline: "2024-07-15",
    isRecurring: true,
    applyLink: "https://www.lpu.in/scholarship/sports.php"
  },
  {
    id: "sp_11",
    name: "Amity University Sports Scholarship",
    provider: "Amity University",
    category: "Sports",
    providerType: "University",
    level: "University",
    incomeLimit: undefined,
    socialGroup: ["All"],
    careerGoal: ["Sports"],
    benefits: "Admission on sports quota + Scholarship on tuition",
    startDate: "2024-04-01",
    deadline: "2024-06-30",
    isRecurring: true,
    applyLink: "https://www.amity.edu"
  },

  // --- ARTS & CREATIVE SCHOLARSHIPS ---
  {
    id: "art_01",
    name: "CCRT Scholarship Scheme",
    provider: "Ministry of Culture",
    category: "Arts",
    providerType: "Government",
    level: "National",
    artField: "Performing Arts",
    socialGroup: ["All"],
    careerGoal: ["Arts"],
    benefits: "₹12,600/year for training in music, dance, theatre",
    startDate: "2023-10-01",
    deadline: "2023-12-31",
    isRecurring: true,
    applyLink: "https://ccrtindia.gov.in"
  },
  {
    id: "art_02",
    name: "Scholarship to Young Artists",
    provider: "Ministry of Culture",
    category: "Arts",
    providerType: "Government",
    level: "National",
    artField: "Creative",
    socialGroup: ["All"],
    careerGoal: ["Arts"],
    benefits: "₹5,000/month for advanced training (18-25 yrs)",
    startDate: "2023-09-01",
    deadline: "2023-11-30",
    isRecurring: true,
    applyLink: "https://www.indiaculture.nic.in"
  },
  {
    id: "art_03",
    name: "Sangeet Natak Akademi Grants",
    provider: "Sangeet Natak Akademi",
    category: "Arts",
    providerType: "Government",
    level: "National",
    artField: "Music",
    socialGroup: ["All"],
    careerGoal: ["Arts"],
    benefits: "Funding for production, training, and preservation",
    startDate: "2024-07-01",
    deadline: "2024-09-30",
    isRecurring: true,
    applyLink: "https://sangeetnatak.gov.in"
  },
  {
    id: "art_04",
    name: "SPIC MACAY Support",
    provider: "SPIC MACAY",
    category: "Arts",
    providerType: "Foundation",
    level: "National",
    artField: "Performing Arts",
    socialGroup: ["All"],
    careerGoal: ["Arts"],
    benefits: "Platform for youth to learn classical arts",
    startDate: "2023-01-01",
    deadline: "2023-12-31",
    isRecurring: true,
    applyLink: "https://spicmacay.org"
  },
  {
    id: "art_05",
    name: "Kalakshetra Foundation Scholarship",
    provider: "Kalakshetra Foundation",
    category: "Arts",
    providerType: "Academy",
    level: "National",
    artField: "Dance",
    socialGroup: ["All"],
    careerGoal: ["Arts"],
    benefits: "Tuition waiver for Bharatanatyam & Music",
    startDate: "2024-03-01",
    deadline: "2024-05-31",
    isRecurring: true,
    applyLink: "https://www.kalakshetra.in"
  },
  {
    id: "art_06",
    name: "Lalit Kala Akademi Scholarships",
    provider: "Lalit Kala Akademi",
    category: "Arts",
    providerType: "Government",
    level: "National",
    artField: "Visual Arts",
    socialGroup: ["All"],
    careerGoal: ["Arts"],
    benefits: "₹20,000/month for visual artists & sculptors",
    startDate: "2024-06-01",
    deadline: "2024-08-31",
    isRecurring: true,
    applyLink: "https://lalitkala.gov.in"
  },
  {
    id: "art_07",
    name: "NSD Scholarship",
    provider: "National School of Drama",
    category: "Arts",
    providerType: "Government",
    level: "National",
    artField: "Theatre",
    socialGroup: ["All"],
    careerGoal: ["Arts"],
    benefits: "Monthly fellowship of ₹8,000 + Production costs",
    startDate: "2024-04-01",
    deadline: "2024-06-30",
    isRecurring: true,
    applyLink: "https://nsd.gov.in"
  },
  {
    id: "art_08",
    name: "FTII Scholarships",
    provider: "FTII Pune",
    category: "Arts",
    providerType: "Government",
    level: "National",
    artField: "Film",
    socialGroup: ["All"],
    careerGoal: ["Arts"],
    benefits: "Merit-based financial aid for cinema students",
    startDate: "2024-05-01",
    deadline: "2024-07-15",
    isRecurring: true,
    applyLink: "https://ftii.ac.in"
  },
  {
    id: "art_09",
    name: "KM Music Conservatory",
    provider: "AR Rahman Foundation",
    category: "Arts",
    providerType: "Private",
    level: "National",
    artField: "Music",
    socialGroup: ["All"],
    careerGoal: ["Arts"],
    benefits: "Full/Partial fee waiver for talented musicians",
    startDate: "2024-03-01",
    deadline: "2024-05-15",
    isRecurring: true,
    applyLink: "https://kmmc.in"
  },
  {
    id: "art_10",
    name: "Shankar Mahadevan Academy",
    provider: "SMA",
    category: "Arts",
    providerType: "Private",
    level: "International",
    artField: "Music",
    socialGroup: ["All"],
    careerGoal: ["Arts"],
    benefits: "Online music scholarships for exceptional talent",
    startDate: "2023-01-01",
    deadline: "2023-12-31",
    isRecurring: true,
    applyLink: "https://shankarmahadevanacademy.com"
  }
];
